#!/usr/bin/env ruby

require_relative 'bootstrap_ar'
database = ENV['PA_ENV'] || 'development'
connect_to database

# # ARGV = [add, equipment]
command = ARGV[0]
equipment_name = ARGV[1]
photo_shoot_name = ARGV[2]


params = { command: command, equipment: { name: equipment_name }, photo_shoot: {name: photo_shoot_name} }
controller =  EquipmentController.new(params)
# params = { command: command, photo_shoot: { name: photo_shoot_name } }
# controller =  PhotoShootController.new(params)
routes = { "add" => :create, "list" => :index, "remove" => :destroy }

# This is a router:
if route = routes[command]
  controller.send route

 end

greeting = "Welcome to Photo Assistant \nWhat would you like to do today?\n\n"
puts greeting

puts <<EOS
Currently supported commands are:
* photoassistant add <equipment>
* photoassistant add p  <photo_shoot>
* photoassistant list <equipment>
* photoassistant remove <equipment>
* photoassistant remove p <photo_shoot>
EOS





