#!/usr/bin/env ruby

require_relative 'bootstrap_ar'
database = ENV['PA_ENV'] || 'development'
connect_to database

command = ARGV[0]

equipment_name = ARGV[1]
serial_number = ARGV[2]
# equipment_type_index = ARGV[3]
# photo_shoot_name = ARGV[3]

greeting = "Welcome to Photo Assistant \nWhat would you like to do today?\n\n"
puts greeting


 puts <<EOS
Currently supported commands are:
* photoassistant add <equipment>
* photoassistant list <equipment>
* photoassistant remove <equipment>
* photoassistant add p  <photo_shoot>
* photoassistant list p  <photo_shoot>
* photoassistant remove p <photo_shoot>
EOS

equipment_params = { command: command, equipment: { name: equipment_name, serial: serial_number} }
controller =  EquipmentController.new(equipment_params)
# params = { command: command, photo_shoot: {name: photo_shoot_name} }
# controller =  PhotoShootController.new(params)
routes = { "add" => :create, "list" => :index, "remove" => :destroy }

# This is a router:
if route = routes[command]
  controller.send route

 end







